name: Java CI with Maven

on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository-
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Validate AMI Script
        run: packer validate AMI.json
